### PR TITLE
Add support for Traditional Chinese language

### PR DESCRIPTION
**Pull request by lukechen116**

### CODE REVIEW

**Comment by 4kimov** [comment]
Hi @lukechen116,

Thank you very much for the PR. I wanted to confirm a few things with you:

1. Is `zh-Hant` the correct language code for this file?
2. Since we currently have `zh`, in your opinion should it be renamed to `zh-Hans`?

**Comment by lukechen116** [comment]
> Hi @lukechen116,
> 
> Thank you very much for the PR. I wanted to confirm a few things with you:
> 
> 1. Is `zh-Hant` the correct language code for this file?
> 2. Since we currently have `zh`, in your opinion should it be renamed to `zh-Hans`?

zh_Hant is compatible with zh_Hant_TW, zh_Hant_HK, and zh_Hant_MO, while zh-Hans is compatible with zh-Hans_CN and zh-Hans_SG. A few terms differ depending on the region.
So you can zh_Hant covers Traditional Chinese language, zh-Hans covers Simplified Chinese language

1. Yes
2. Yes
 
But I don't know how your framework handles i18n. Does it support the "language[_script][_region]" recommended by W3C? You can try to be compatible with the ancient tags zh_TW for zh_Hant and zh_CN for zh-Hans.

**Comment by 4kimov** [comment]
Hi @lukechen116, thank you for elaborating.

I'd have to test the i18n compatibility a bit more, but for now I've been trying to see what other websites have been doing. Judging from quick research, it seems the traditional `zh-cn` and `zh-tw` are more common around the web. I'll need a bit of time to research more, so I'll keep this PR open in the meantime.

Thank you again for the feedback.

**Comment by 4kimov** [comment]
Hi @lukechen116, I'm going to merge this for now & make some changes to the site. I think for now, I'll leave simplified under `/zh` and add traditional under `/zh-tw`. Once the changes are live, I could use your help on verifying the translation is accurate. Thank you for the PR.

**Comment by 4kimov** [comment]
Chinese Traditional added @ https://sqids.org/zh-tw with some changes + latest text updates.

@lukechen116 Does https://github.com/sqids/sqids-i18n/blob/next/archive/languages/zh-tw.json look good?

**Pull request merged**
